default: &default
  store_options:
    # Cap age of oldest cache entry - for answer storage, we keep it short
    max_age: <%= 1.hour.to_i %>
    max_size: <%= 512.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
