default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 5
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
